<?php
/** Public homepage: browse KICD subjects and generated lessons. No login required. */

declare(strict_types=1);

require_once __DIR__ . '/config/database.php';
require_once __DIR__ . '/config/helpers.php';
secure_session_start();

$pdo = db();
$subjects = $pdo->query('SELECT id, code, name, strand, grade_level FROM subjects ORDER BY name')->fetchAll();
$subjectCount = count($subjects);
$lessonCount = (int) $pdo->query('SELECT COUNT(*) FROM lessons')->fetchColumn();

$pageTitle    = 'Browse lessons';
$publicHeader = true;
require __DIR__ . '/includes/header.php';
?>
<div class="page-head">
    <div class="page-head-main">
        <span class="page-head-icon" aria-hidden="true">📚</span>
        <div>
            <h1>Browse lessons</h1>
            <p class="page-head-sub">Lesson plans grounded in the KICD curriculum, generated by MwalimuPlus teachers — free to read, no account needed.</p>
        </div>
    </div>
</div>

<section class="stat-grid">
    <div class="stat-card">
        <div>
            <p class="stat-label">Subjects</p>
            <p class="stat-value"><?= $subjectCount ?></p>
        </div>
        <span class="stat-icon stat-icon-green" aria-hidden="true">📚</span>
    </div>
    <div class="stat-card">
        <div>
            <p class="stat-label">Lessons available</p>
            <p class="stat-value"><?= $lessonCount ?></p>
        </div>
        <span class="stat-icon stat-icon-violet" aria-hidden="true">📝</span>
    </div>
</section>

<section class="panel" id="subjects">
    <h2>Subjects</h2>
    <?php if ($subjects): ?>
        <div class="card-grid">
            <?php foreach ($subjects as $subject): ?>
                <a class="card subject-card" href="browse-subject.php?id=<?= (int) $subject['id'] ?>">
                    <span class="subject-code"><?= htmlspecialchars($subject['code']) ?></span>
                    <h3><?= htmlspecialchars($subject['name']) ?></h3>
                    <p class="muted"><?= htmlspecialchars($subject['strand']) ?></p>
                </a>
            <?php endforeach; ?>
        </div>
    <?php else: ?>
        <p class="muted">No subjects available yet.</p>
    <?php endif; ?>
</section>

<?php require __DIR__ . '/includes/footer.php'; ?>
