<?php
/** Public homepage: browse KICD subjects and generated lessons. No login required. */

declare(strict_types=1);

require_once __DIR__ . '/config/database.php';
require_once __DIR__ . '/config/helpers.php';
secure_session_start();
enforce_not_in_maintenance();

$pdo = db();
$subjects = $pdo->query('SELECT id, code, name, strand, grade_level FROM subjects ORDER BY name')->fetchAll();
$subjectCount = count($subjects);
$lessonCount = (int) $pdo->query('SELECT COUNT(*) FROM lessons')->fetchColumn();

$schemeStmt = $pdo->prepare(
    "SELECT sc.id, sc.title, sc.term, sc.status, sc.created_at, s.name AS subject_name
       FROM schemes sc
       JOIN subjects s ON s.id = sc.subject_id
      WHERE sc.is_hidden = 0 AND sc.status <> 'UNKNOWN' AND sc.payload IS NOT NULL
      ORDER BY sc.created_at DESC
      LIMIT 12"
);
$schemeStmt->execute();
$publicSchemes = $schemeStmt->fetchAll();
$schemeCount = (int) $pdo->query('SELECT COUNT(*) FROM schemes WHERE is_hidden = 0 AND status <> \'UNKNOWN\'')->fetchColumn();

$pageTitle    = 'Browse lessons';
$publicHeader = true;
require __DIR__ . '/includes/header.php';
?>
<div class="page-head">
    <div class="page-head-main">
        <span class="page-head-icon" aria-hidden="true">📚</span>
        <div>
            <h1>Browse lessons &amp; schemes</h1>
            <p class="page-head-sub">Lesson plans and schemes of work grounded in the KICD curriculum, generated by MwalimuPlus teachers — free to read, no account needed.</p>
        </div>
    </div>
</div>

<section class="stat-grid">
    <div class="stat-card">
        <div>
            <p class="stat-label">Subjects</p>
            <p class="stat-value"><?= $subjectCount ?></p>
        </div>
        <span class="stat-icon stat-icon-green" aria-hidden="true">📚</span>
    </div>
    <div class="stat-card">
        <div>
            <p class="stat-label">Lessons available</p>
            <p class="stat-value"><?= $lessonCount ?></p>
        </div>
        <span class="stat-icon stat-icon-violet" aria-hidden="true">📝</span>
    </div>
    <div class="stat-card">
        <div>
            <p class="stat-label">Public schemes</p>
            <p class="stat-value"><?= $schemeCount ?></p>
        </div>
        <span class="stat-icon stat-icon-blue" aria-hidden="true">🗓️</span>
    </div>
</section>

<section class="panel" id="schemes">
    <h2>Schemes of Work</h2>
    <?php if ($publicSchemes): ?>
        <div class="card-grid">
            <?php foreach ($publicSchemes as $scheme): ?>
                <a class="card" href="browse-scheme.php?id=<?= (int) $scheme['id'] ?>">
                    <span class="subject-code"><?= htmlspecialchars($scheme['subject_name']) ?></span>
                    <h3><?= htmlspecialchars($scheme['title']) ?></h3>
                    <p class="muted">Term <?= (int) $scheme['term'] ?> · <span class="badge badge-<?= strtolower($scheme['status']) ?>"><?= htmlspecialchars($scheme['status']) ?></span></p>
                    <p class="muted" style="font-size:.82rem;margin-top:.5rem"><?= htmlspecialchars(date('d M Y', strtotime($scheme['created_at']))) ?></p>
                </a>
            <?php endforeach; ?>
        </div>
    <?php else: ?>
        <p class="muted">No public schemes yet — teachers can share their schemes from their dashboard.</p>
    <?php endif; ?>
</section>

<section class="panel" id="subjects">
    <h2>Subjects</h2>
    <?php if ($subjects): ?>
        <div class="card-grid">
            <?php foreach ($subjects as $subject): ?>
                <a class="card subject-card" href="browse-subject.php?id=<?= (int) $subject['id'] ?>">
                    <span class="subject-code"><?= htmlspecialchars($subject['code']) ?></span>
                    <h3><?= htmlspecialchars($subject['name']) ?></h3>
                    <p class="muted"><?= htmlspecialchars($subject['strand']) ?></p>
                </a>
            <?php endforeach; ?>
        </div>
    <?php else: ?>
        <p class="muted">No subjects available yet.</p>
    <?php endif; ?>
</section>

<?php require __DIR__ . '/includes/footer.php'; ?>
