<?php
/** Superadmin: analytics — teachers, subjects, lessons generated, AI usage. */

declare(strict_types=1);

require_once __DIR__ . '/config/database.php';
require_once __DIR__ . '/includes/require-superadmin.php';

$pdo = db();

$signupsByMonth = $pdo->query(
    "SELECT DATE_FORMAT(created_at, '%Y-%m') AS ym, COUNT(*) AS n
       FROM users
      WHERE role = 'teacher'
      GROUP BY ym
      ORDER BY ym DESC
      LIMIT 6"
)->fetchAll();

$lessonsBySubject = $pdo->query(
    'SELECT s.name, COUNT(*) AS n
       FROM lessons l
       JOIN subjects s ON s.id = l.subject_id
      GROUP BY s.id, s.name
      ORDER BY n DESC
      LIMIT 10'
)->fetchAll();

$topTeachers = $pdo->query(
    "SELECT u.name, COUNT(*) AS n
       FROM lessons l
       JOIN users u ON u.id = l.user_id
      GROUP BY u.id, u.name
      ORDER BY n DESC
      LIMIT 10"
)->fetchAll();

$pageTitle    = 'Analytics';
$activeNav    = 'admin-analytics';
$showHeader   = true;
$adminShell   = true;
$pageIcon     = '📊';
$pageHeading  = 'Analytics';
$pageSubtitle = 'Teachers, subjects, and lessons generated across the whole app.';
$breadcrumbs  = [
    ['label' => 'Super Admin', 'href' => 'superadmin.php'],
    ['label' => 'Analytics'],
];
require __DIR__ . '/includes/header.php';
?>
<div class="dashboard-layout">
    <div class="dashboard-main">
        <section class="panel" style="margin-top:0;">
            <h2>Lessons generated by subject</h2>
            <?php if ($lessonsBySubject): ?>
                <table class="table">
                    <thead><tr><th>Subject</th><th>Lessons</th></tr></thead>
                    <tbody>
                    <?php foreach ($lessonsBySubject as $row): ?>
                        <tr><td><?= htmlspecialchars($row['name']) ?></td><td><?= (int) $row['n'] ?></td></tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
            <?php else: ?>
                <p class="muted">No lessons generated yet.</p>
            <?php endif; ?>
        </section>

        <section class="panel">
            <h2>Most active teachers</h2>
            <?php if ($topTeachers): ?>
                <table class="table">
                    <thead><tr><th>Teacher</th><th>Lessons generated</th></tr></thead>
                    <tbody>
                    <?php foreach ($topTeachers as $row): ?>
                        <tr><td><?= htmlspecialchars($row['name']) ?></td><td><?= (int) $row['n'] ?></td></tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
            <?php else: ?>
                <p class="muted">No lessons generated yet.</p>
            <?php endif; ?>
        </section>
    </div>

    <div class="dashboard-sidebar">
        <section class="panel" style="margin-top:0;">
            <h2>Teacher signups (last 6 months)</h2>
            <?php if ($signupsByMonth): ?>
                <table class="table">
                    <thead><tr><th>Month</th><th>Signups</th></tr></thead>
                    <tbody>
                    <?php foreach ($signupsByMonth as $row): ?>
                        <tr><td><?= htmlspecialchars($row['ym']) ?></td><td><?= (int) $row['n'] ?></td></tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
            <?php else: ?>
                <p class="muted">No signups yet.</p>
            <?php endif; ?>
        </section>

        <section class="panel">
            <h2>AI usage</h2>
            <p class="muted">Per-request token/cost tracking isn't logged yet — every AI call goes straight to the provider without a usage record. Add logging in <code>config/claude.php</code>'s request path to populate this.</p>
        </section>
    </div>
</div>

<?php require __DIR__ . '/includes/footer.php'; ?>
